### ISSUE TITLE
ValueError: Bin edges must be unique

### ISSUE THREAD

**Issue by MatteoRiva95** [linhuawang/spImpute#4]
Hello everyone,

I am trying to follow the tutorial, running these commands:

rd_1 = ReST(path="/path/to/spatial/")
rd.preprocess(species='Human', hvg_prop=0.8, n_pcs=30)

I also tried with different inputs (adata, coordinates, csv, df with integers numbers), but it always returns this error:

ValueError                                Traceback (most recent call last)
Cell In[42], line 2
      1 rd_1 = ReST(path="/path/to/spatial/")
----> 2 rd.preprocess(species='Human', hvg_prop=0.8, n_pcs=30)

File ~/Documents/Spatial/compiti/MIST/MIST/ReST.py:134, in ReST.preprocess(self, hvg_prop, species, n_pcs, min_read_count, min_cell_count, corr_methods)
    132 # Procedure 4: Apply PCA using highly variable genes
    133 if hvg_prop is not None:
--> 134 	sc.pp.highly_variable_genes(adata, flavor="seurat", n_top_genes=int(hvg_prop * adata.shape[1]))
    135 else:
    136 	sc.pp.highly_variable_genes(adata)

File ~/.conda/envs/MIST/lib/python3.9/site-packages/scanpy/preprocessing/_highly_variable_genes.py:431, in highly_variable_genes(adata, layer, n_top_genes, min_disp, max_disp, min_mean, max_mean, span, n_bins, flavor, subset, inplace, batch_key, check_values)
    419     return _highly_variable_genes_seurat_v3(
    420         adata,
    421         layer=layer,
   (...)
    427         inplace=inplace,
    428     )
    430 if batch_key is None:
--> 431     df = _highly_variable_genes_single_batch(
    432         adata,
    433         layer=layer,
    434         min_disp=min_disp,
    435         max_disp=max_disp,
    436         min_mean=min_mean,
    437         max_mean=max_mean,
    438         n_top_genes=n_top_genes,
    439         n_bins=n_bins,
    440         flavor=flavor,
    441     )
    442 else:
    443     sanitize_anndata(adata)

File ~/.conda/envs/MIST/lib/python3.9/site-packages/scanpy/preprocessing/_highly_variable_genes.py:215, in _highly_variable_genes_single_batch(adata, layer, min_disp, max_disp, min_mean, max_mean, n_top_genes, n_bins, flavor)
    213 df['dispersions'] = dispersion
    214 if flavor == 'seurat':
--> 215     df['mean_bin'] = pd.cut(df['means'], bins=n_bins)
    216     disp_grouped = df.groupby('mean_bin')['dispersions']
    217     disp_mean_bin = disp_grouped.mean()

File ~/.conda/envs/MIST/lib/python3.9/site-packages/pandas/core/reshape/tile.py:292, in cut(x, bins, right, labels, retbins, precision, include_lowest, duplicates, ordered)
    289     if (np.diff(bins.astype("float64")) < 0).any():
    290         raise ValueError("bins must increase monotonically.")
--> 292 fac, bins = _bins_to_cuts(
    293     x,
    294     bins,
    295     right=right,
    296     labels=labels,
    297     precision=precision,
    298     include_lowest=include_lowest,
    299     dtype=dtype,
    300     duplicates=duplicates,
    301     ordered=ordered,
    302 )
    304 return _postprocess_for_cut(fac, bins, retbins, dtype, original)

File ~/.conda/envs/MIST/lib/python3.9/site-packages/pandas/core/reshape/tile.py:419, in _bins_to_cuts(x, bins, right, labels, precision, include_lowest, dtype, duplicates, ordered)
    417 if len(unique_bins) < len(bins) and len(bins) != 2:
    418     if duplicates == "raise":
--> 419         raise ValueError(
    420             f"Bin edges must be unique: {repr(bins)}.\n"
    421             f"You can drop duplicate edges by setting the 'duplicates' kwarg"
    422         )
    423     else:
    424         bins = unique_bins

ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg

Can you help me, please? I do not understand what I am doing wrong!
Moreover, I do not understand how I can obtain a df like the raw.csv one present in test_data.

Please, any help would be super appreciated.

**Comment by MatteoRiva95** [comment]
Sorry, I just solved the issue (my bad, a typo error in the two command lines...).
But now if I try to run the imputation:

imputed = rd_1.impute(ncores=1, nExperts=3)

it gives back this error:

---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
Cell In[50], line 2
      1 ## Run imputation
----> 2 imputed = rd_1.impute(ncores=1, nExperts=3)

File ~/Documents/Spatial/compiti/MIST/MIST/ReST.py:533, in ReST.impute(self, method, n_neighbors, ncores, nExperts, layer, thre)
    531 imputer = Imputer(method, rdata)
    532 nodes = self.nodes
--> 533 imputed_data = imputer.fit_transform(n_neighbors=n_neighbors, 
    534 	ncores=ncores, nExperts=nExperts, layer=layer, thre=thre)
    535 return imputed_data

File ~/Documents/Spatial/compiti/MIST/MIST/imputers.py:61, in Imputer.fit_transform(self, n_neighbors, select, ncores, nExperts, thre, layer)
     56 coord_df.columns= ["x", "y"]
     58 cor_df = pd.DataFrame(data=corrs,
     59 						index=self.data.adata.obs_names.copy(),
     60 						columns=self.data.adata.obs_names.copy())
---> 61 return spKNN(data, coord_df, cor_df, thre)

File ~/Documents/Spatial/compiti/MIST/MIST/imputers.py:137, in spKNN(data, coord_df, cor_df, thre)
    124 """"A base-line method that estimate missing values by averaging
    125  no more than 4 spatially adjacent spots.
    126 
   (...)
    134 Imputed gene expression as data frame.
    135 """
    136 ## construct graph
--> 137 nodes = neighbors.construct_graph(coord_df)
    138 print("Graph constructed.")
    139 nb_df = pd.DataFrame(index=data.index, columns=data.index,
    140 			data=np.zeros((data.shape[0], data.shape[0])))

File ~/Documents/Spatial/compiti/MIST/MIST/neighbors.py:197, in construct_graph(meta_data, radius)
    195 for node1 in nodes:
    196 	for node2 in nodes:
--> 197 		dist = np.linalg.norm(np.array((node1.x, node1.y)) -
    198 			np.array((node2.x, node2.y)))
    199 		if dist < radius:
    200 			node1.add_neighbor(node2)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> None

**Comment by linhuawang** [comment]
Thanks for letting me know that you solved it @MatteoRiva95
